{% set name = "unearth" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/unearth-{{ version }}.tar.gz
  sha256: 4b7bfbd7d34a11673d80dfae7fabbf921c139aac78383fb0ca16a90d3b53a66e

build:
  skip: true  # [py<37]
  script: 
    - python -m pip install --no-deps --ignore-installed .
  entry_points:
    - unearth = unearth.__main__:cli
  number: 0

requirements:
  host:
    - pip <22.2
    - python
    - pdm-pep517
    - setuptools
    - wheel
  run:
    - cached-property >=1.5.2  # [py<38]
    - packaging >=20
    - python
    - requests >=2.25

test:
  imports:
    - unearth
  source_files:
    - tests
  commands:
  # Skipping test_session_with_selfsigned_ca because pytest-httpserver is not on defaults
    - pytest tests -k "not test_session_with_selfsigned_ca"
    - pip check
  requires:
    - pip
    - pytest >=6.1
    - flask >=2.1.2
    - requests-wsgi-adapter >=0.4.1
    - trustme >=0.9.0
    - keyring
    - openssl <3.0.0

about:
  home: https://pypi.org/project/unearth/
  summary: A utility to fetch and download python packages
  license: MIT
  license_family: MIT
  license_file: LICENSE
  license_url: https://github.com/frostming/unearth/blob/main/LICENSE
  dev_url: https://github.com/frostming/unearth
  doc_url: https://unearth.readthedocs.io/en/latest/
  doc_source_url: https://github.com/frostming/unearth/tree/main/docs

extra:
  recipe-maintainers:
    - theAeon
